var whStemmer = new Snowball();
var whBaseNameList = [
/*0*/ "Education.html",
/*1*/ "Summary.html",
/*2*/ "technical_skills.html",
/*3*/ "Experience.html"
];
var whTitleList = [
/*0*/ "Section 3. Education",
/*1*/ "PBJ&#39;s Resume",
/*2*/ "Section 4. Technical Skills",
/*3*/ "Section 2. Experience"
];
// 66 words.
var whWordMap = {
"through": [1],
"educatioo": [0],
"inform": [0],
"cortlaad": [0],
"offic": [2],
"project": [2],
"wrii": [0],
"microsoft": [2],
"that": [1],
"oracl": [2],
"xml": [2],
"state": [0],
"htmm": [2],
"oxygen": [2],
"profession": [0],
"new": [0],
"is": [1],
"tool": [2],
"databas": [2],
"colleg": [0],
"at": [0],
"miirosoft": [2],
"immediateyi": [1],
"soluuion": [2],
"pbj": [1],
"juli": [3],
"philosophi": [0],
"present": [3],
"sustain": [1],
"applicatton": [2],
"scienc": [0],
"fico": [3],
"server": [2],
"librari": [0],
"detail-ori": [1],
"yook": [0],
"compani": [1],
"univers": [0],
"seek": [1],
"resum": [1],
"sql": [2],
"mission-driven": [1],
"world": [1],
"softwar": [2],
"and": [0,1],
"syracus": [0],
"of": [0],
"skill": [2],
"rafael": [3],
"ca": [3],
"avail": [1],
"editor": [2],
"san": [3],
"technic": [[1,2,3]],
"summmri": [1],
"innov": [1],
"master": [0],
"the": [1],
"experienn": [3],
"chang": [1],
"manngement": [2],
"xll": [2],
"writer": [[1,3]],
"to": [1],
"languug": [2],
"db": [2]
};
